### ISSUE TITLE
Alt+Tabbing out and locks up after coming back and requires a reload of the page

### ISSUE THREAD

**Issue by ortiza5** [Pathduck/spatialnavigation#2]
When switching programs with keyboard shortcuts like `Alt` + `Tab`, the extension stops working when returning to the browser.

The problem is likely that the `set` of keys held down is not properly cleared on loss of tab focus. This leads to the keys being stuck in the `set` that the hotkeys are compared against, so no hotkeys will match.

**Comment by Pathduck** [comment]
Seems to be fixed here after a quick test, well done 👍

**Comment by ortiza5** [comment]
Glad it worked! Just had to search through my old code to see what I figured out back then.
