### ISSUE TITLE
Options page should be made more easy to get to

### ISSUE THREAD

**Issue by ortiza5** [Pathduck/spatialnavigation#7]
The options page should be accessible by simple `left-clicking` the extension's icon in the address bar.

It doesn't seem like the extension needs a popup pageAction, so making the options open seems like the best use of the extension's icon.

**Comment by Pathduck** [comment]
I think this can be closed, the options page is available from clicking the icon. I believe there was a bug at some point in Vivaldi where the option didn't appear for some reason? Anyway, this is *sufficient enough* for its purpose 😄
